    use rust_decimal::Decimal;

    use super::*;
    use crate::agent::{
        AgentActionExpectancies, AgentRecommendations, AgentSession, AgentStructureState,
        AgentSymbolState, AgentThread, AgentWakeState,
    };
    use crate::live_snapshot::LiveScorecard;
    use crate::ontology::AgentKnowledgeLink;
    use crate::agent_llm::AgentNarration;
    use crate::live_snapshot::{LiveStressSnapshot, LiveMarketRegime};

    #[test]
    fn builds_operational_snapshot_from_projection_views() {
        let live_snapshot = LiveSnapshot {
            tick: 7,
            timestamp: "2026-03-29T15:00:00Z".into(),
            market: LiveMarket::Hk,
            stock_count: 1,
            edge_count: 1,
            hypothesis_count: 0,
            observation_count: 0,
            active_positions: 0,
            active_position_nodes: vec![],
            market_regime: LiveMarketRegime {
                bias: "neutral".into(),
                confidence: Decimal::ZERO,
                breadth_up: Decimal::ZERO,
                breadth_down: Decimal::ZERO,
                average_return: Decimal::ZERO,
                directional_consensus: None,
                pre_market_sentiment: None,
            },
            stress: LiveStressSnapshot {
                composite_stress: Decimal::ZERO,
                sector_synchrony: None,
                pressure_consensus: None,
                momentum_consensus: None,
                pressure_dispersion: None,
                volume_anomaly: None,
            },
            scorecard: LiveScorecard {
                total_signals: 0,
                resolved_signals: 0,
                hits: 0,
                misses: 0,
                hit_rate: Decimal::ZERO,
                mean_return: Decimal::ZERO,
            },
            tactical_cases: vec![crate::live_snapshot::LiveTacticalCase {
                setup_id: "setup:700.HK".into(),
                symbol: "700.HK".into(),
                title: "Long 700".into(),
                action: "enter".into(),
                confidence: Decimal::ZERO,
                confidence_gap: Decimal::ZERO,
                heuristic_edge: Decimal::ZERO,
                entry_rationale: "test".into(),
                family_label: Some("Flow".into()),
                counter_label: None,
            }],
            hypothesis_tracks: vec![],
            top_signals: vec![],
            convergence_scores: vec![],
            pressures: vec![],
            backward_chains: vec![],
            causal_leaders: vec![],
            events: vec![],
            cross_market_signals: vec![],
            cross_market_anomalies: vec![],
            structural_deltas: vec![],
            propagation_senses: vec![],
            lineage: vec![],
        };
        let snapshot = AgentSnapshot {
            tick: 7,
            timestamp: "2026-03-29T15:00:00Z".into(),
            market: LiveMarket::Hk,
            market_regime: LiveMarketRegime {
                bias: "neutral".into(),
                confidence: Decimal::ZERO,
                breadth_up: Decimal::ZERO,
                breadth_down: Decimal::ZERO,
                average_return: Decimal::ZERO,
                directional_consensus: None,
                pre_market_sentiment: None,
            },
            stress: LiveStressSnapshot {
                composite_stress: Decimal::ZERO,
                sector_synchrony: None,
                pressure_consensus: None,
                momentum_consensus: None,
                pressure_dispersion: None,
                volume_anomaly: None,
            },
            wake: AgentWakeState {
                should_speak: false,
                priority: Decimal::ZERO,
                headline: Some("headline".into()),
                summary: vec![],
                focus_symbols: vec!["700.HK".into()],
                reasons: vec![],
                suggested_tools: vec![],
            },
            world_state: None,
            backward_reasoning: None,
            notices: vec![],
            active_structures: vec![AgentStructureState {
                symbol: "700.HK".into(),
                sector: Some("Technology".into()),
                setup_id: Some("setup:700.HK".into()),
                title: "Long 700".into(),
                action: "enter".into(),
                status: None,
                age_ticks: None,
                status_streak: None,
                confidence: Decimal::ZERO,
                confidence_change: None,
                confidence_gap: Some(Decimal::ZERO),
                transition_reason: None,
                contest_state: None,
                current_leader: None,
                leader_streak: None,
                leader_transition_summary: None,
                thesis_family: Some("Flow".into()),
                action_expectancies: AgentActionExpectancies::default(),
                expected_net_alpha: Some(Decimal::ZERO),
                alpha_horizon: Some("intraday:10t".into()),
                invalidation_rule: Some("bid disappears".into()),
            }],
            recent_transitions: vec![],
            sector_flows: vec![],
            symbols: vec![AgentSymbolState {
                symbol: "700.HK".into(),
                sector: Some("Technology".into()),
                structure: None,
                signal: None,
                depth: None,
                brokers: None,
                invalidation: None,
                pressure: None,
                active_position: None,
                latest_events: vec![],
            }],
            events: vec![],
            cross_market_signals: vec![],
            context_priors: vec![],
            macro_event_candidates: vec![],
            macro_events: vec![],
            knowledge_links: vec![AgentKnowledgeLink {
                link_id: "link:1".into(),
                relation: crate::ontology::KnowledgeRelation::ImpactsSymbol,
                source: crate::ontology::macro_event_knowledge_node_ref("macro:1", "headline"),
                target: crate::ontology::symbol_knowledge_node_ref("700.HK"),
                confidence: Decimal::ZERO,
                attributes: crate::ontology::KnowledgeLinkAttributes::Generic,
                rationale: None,
            }],
        };
        let session = AgentSession {
            tick: 7,
            timestamp: "2026-03-29T15:00:00Z".into(),
            market: LiveMarket::Hk,
            should_speak: false,
            active_thread_count: 1,
            focus_symbols: vec!["700.HK".into()],
            active_threads: vec![AgentThread {
                symbol: "700.HK".into(),
                sector: Some("Technology".into()),
                status: "active".into(),
                first_tick: 7,
                last_tick: 7,
                idle_ticks: 0,
                turns_observed: 1,
                priority: Decimal::ZERO,
                title: Some("700 thread".into()),
                headline: None,
                latest_summary: Some("watch".into()),
                last_transition: None,
                current_leader: None,
                invalidation_status: None,
                reasons: vec![],
            }],
            recent_turns: vec![],
        };
        let recommendations = AgentRecommendations {
            tick: 7,
            timestamp: "2026-03-29T15:00:00Z".into(),
            market: LiveMarket::Hk,
            regime_bias: "neutral".into(),
            total: 0,
            market_recommendation: None,
            decisions: vec![],
            items: vec![],
            knowledge_links: vec![],
        };
        let narration = AgentNarration {
            tick: 7,
            timestamp: "2026-03-29T15:00:00Z".into(),
            market: LiveMarket::Hk,
            should_alert: false,
            alert_level: "normal".into(),
            source: "local".into(),
            headline: None,
            message: None,
            bullets: vec![],
            focus_symbols: vec![],
            tags: vec![],
            primary_action: None,
            confidence_band: None,
            what_changed: vec![],
            why_it_matters: None,
            watch_next: vec![],
            what_not_to_do: vec![],
            fragility: vec![],
            recommendation_ids: vec![],
            market_summary_5m: Some("summary".into()),
            market_recommendation: None,
            dominant_lenses: vec![],
            action_cards: vec![],
        };

        let operational =
            build_operational_snapshot(
                &live_snapshot,
                &snapshot,
                &session,
                &recommendations,
                Some(&narration),
            )
            .expect("operational snapshot");

        assert_eq!(operational.market_session.id.0, "market_session:hk:7");
        assert_eq!(operational.symbols.len(), 1);
        assert_eq!(operational.cases.len(), 1);
        assert_eq!(operational.threads.len(), 1);
        assert_eq!(operational.workflows.len(), 1);
        assert_eq!(operational.market_session.market_summary.as_deref(), Some("summary"));
    }
